name: Assign Issue to User

on:
  issues:
    types: ["opened"]

jobs:
  assignUser:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
            assignees: ${{ github.event.issue.user.login }}
            repo-token: ${{ secrets.GH_TOKEN }}